### ISSUE TITLE
Sphinx build error nixos 23.11

### ISSUE THREAD

**Issue by dpolakovics** [Mic92/sops-nix#448]
Hello,

when trying to upgrade to 23.11 i get an error from sphinx.

```
Exception occurred:
  File "/build/Python-3.9.18/Doc/tools/extensions/pyspecific.py", line 361, in run
    label = translators['sphinx'].gettext(label)
            ~~~~~~~~~~~^^^^^^^^^^
KeyError: 'sphinx'
The full traceback has been saved in /build/sphinx-err-vhltl___.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
error: builder for '/nix/store/2q6qf6cmj7fyvgrgd7pvdzzx9dmn0xky-python3.9-3.9.18-doc.drv' failed with exit code 2
error: 1 dependencies of derivation '/nix/store/bf5qjcis4igvzgl6wlkyqaf6rfd8xz5f-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/nw7gkwddw6qq9y66dwwi5mb5zqyrkjjh-nixos-system-git-23.11.1209.933d7dc15509.drv' failed to build
```

It occurs on the aws-cli module.

Best regards,
Dominik

**Comment by dpolakovics** [comment]
Ah sorry meant aws-sdk

Here is the part where it starts going wrong.

```
building '/nix/store/2a63a99v1cj6cx24nfva61llgx12f3kj-sops-install-secrets-0.0.1-go-modules.drv'...
Sourcing sphinx-hook
unpacking sources
unpacking source archive /nix/store/asjlmba027x9l540mc7cb6rl827qhqzl-source
source root is source
unpacking sources
patching sources
unpacking source archive /nix/store/mqm1nwm3dj4lwq83ss8cw0n1hs6yc38z-Python-3.9.18.tar.xz
updateAutotoolsGnuConfigScriptsPhase
configuring
building
go: downloading github.com/ProtonMail/go-crypto v0.0.0-20220623141421-5afb4c282135
go: downloading golang.org/x/crypto v0.16.0
go: downloading github.com/Mic92/ssh-to-age v0.0.0-20220621201837-f006bbe6b80b
go: downloading github.com/joho/godotenv v1.5.1
go: downloading github.com/mozilla-services/yaml v0.0.0-20201007153854-c369669a6625
go: downloading go.mozilla.org/sops/v3 v3.7.3
go: downloading golang.org/x/sys v0.15.0
go: downloading filippo.io/edwards25519 v1.0.0
go: downloading github.com/sirupsen/logrus v1.8.1
go: downloading github.com/fatih/color v1.13.0
go: downloading github.com/mitchellh/go-wordwrap v1.0.1
go: downloading gopkg.in/urfave/cli.v1 v1.20.0
go: downloading github.com/goware/prefixer v0.0.0-20160118172347-395022866408
go: downloading golang.org/x/net v0.17.0
go: downloading github.com/mattn/go-colorable v0.1.12
go: downloading github.com/mattn/go-isatty v0.0.14
go: downloading github.com/golang/protobuf v1.5.3
go: downloading google.golang.org/grpc v1.56.3
source root is Python-3.9.18
setting SOURCE_DATE_EPOCH to timestamp 1692901018 of file Python-3.9.18/Misc/NEWS
patching sources
updateAutotoolsGnuConfigScriptsPhase
Updating Autotools / GNU config script to a newer upstream version: ./config.sub
Updating Autotools / GNU config script to a newer upstream version: ./config.guess
installing
no Makefile or custom installPhase, doing nothing
post-installation fixup
buildSphinxPhase
Executing buildSphinxPhase
Executing sphinx-build with html builder
go: downloading google.golang.org/protobuf v1.30.0
Running Sphinx v7.2.6
go: downloading github.com/aws/aws-sdk-go v1.44.51
/build/Python-3.9.18/Doc/tools/extensions/pyspecific.py:30: RemovedInSphinx80Warning: The alias 'sphinx.util.status_iterator' is deprecated, use 'sphinx.util.display.status_iterator' instead. Check CHANGES for Sphinx API modifications.
  from sphinx.util import status_iterator, logging
making output directory... done
locale_dir /build/Python-3.9.18/Doc/locales/en/LC_MESSAGES does not exist
locale_dir /build/Python-3.9.18/Doc/locales/en/LC_MESSAGES does not exist
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 488 source files that are out of date
updating environment: locale_dir /build/Python-3.9.18/Doc/locales/en/LC_MESSAGES does not exist
[new config] 488 added, 0 changed, 0 removed
reading sources... [  0%] about
reading sources... [  0%] bugs
reading sources... [  1%] c-api/abstract
reading sources... [  1%] c-api/allocation
reading sources... [  1%] c-api/apiabiversion
reading sources... [  1%] c-api/arg

Traceback (most recent call last):
  File "/nix/store/y7j1s531qwjqwbcg5p4zpdrxxh22bfnf-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/cmd/build.py", line 298, in build_main
    app.build(args.force_all, args.filenames)
  File "/nix/store/y7j1s531qwjqwbcg5p4zpdrxxh22bfnf-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/application.py", line 355, in build
    self.builder.build_update()
  File "/nix/store/y7j1s531qwjqwbcg5p4zpdrxxh22bfnf-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/nix/store/y7j1s531qwjqwbcg5p4zpdrxxh22bfnf-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 313, in build
    updated_docnames = set(self.read())
                           ^^^^^^^^^^^
  File "/nix/store/y7j1s531qwjqwbcg5p4zpdrxxh22bfnf-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 420, in read
    self._read_serial(docnames)
  File "/nix/store/y7j1s531qwjqwbcg5p4zpdrxxh22bfnf-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 441, in _read_serial
    self.read_doc(docname)
  File "/nix/store/y7j1s531qwjqwbcg5p4zpdrxxh22bfnf-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 498, in read_doc
    publisher.publish()
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/core.py", line 234, in publish
    self.document = self.reader.read(self.source, self.parser,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/y7j1s531qwjqwbcg5p4zpdrxxh22bfnf-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/io.py", line 105, in read
    self.parse()
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "/nix/store/y7j1s531qwjqwbcg5p4zpdrxxh22bfnf-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/parsers.py", line 81, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 169, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2785, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
                   ^^^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 3024, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
                   ^^^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2785, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
                   ^^^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2735, in indent
    newline_offset, blank_finish = self.nested_list_parse(
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 316, in nested_list_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2921, in indent
    itemnode, blank_finish = self.definition_list_item(context)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2856, in definition_list_item
    self.nested_parse(indented, input_offset=line_offset, node=definition)
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2357, in explicit_markup
    self.explicit_list(blank_finish)
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2382, in explicit_list
    newline_offset, blank_finish = self.nested_list_parse(
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 316, in nested_list_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2660, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2367, in explicit_construct
    return method(self, expmatch)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2104, in directive
    return self.run_directive(
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/g5ijs5la181iga70qbiprfxn89xxl43d-python3.11-docutils-0.20.1/lib/python3.11/site-packages/docutils/parsers/rst/states.py", line 2154, in run_directive
    result = directive_instance.run()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/Python-3.9.18/Doc/tools/extensions/pyspecific.py", line 361, in run
    label = translators['sphinx'].gettext(label)
            ~~~~~~~~~~~^^^^^^^^^^
KeyError: 'sphinx'

Exception occurred:
  File "/build/Python-3.9.18/Doc/tools/extensions/pyspecific.py", line 361, in run
    label = translators['sphinx'].gettext(label)
            ~~~~~~~~~~~^^^^^^^^^^
The full traceback has been saved in /build/sphinx-err-vhltl___.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
error: builder for '/nix/store/2q6qf6cmj7fyvgrgd7pvdzzx9dmn0xky-python3.9-3.9.18-doc.drv' failed with exit code 2
error: 1 dependencies of derivation '/nix/store/bf5qjcis4igvzgl6wlkyqaf6rfd8xz5f-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/nw7gkwddw6qq9y66dwwi5mb5zqyrkjjh-nixos-system-git-23.11.1209.933d7dc15509.drv' failed to build
```

my implementation of sops is like:
```
  imports = [
    "${builtins.fetchTarball "https://github.com/Mic92/sops-nix/archive/master.tar.gz"}/modules/sops"
  ];
```

**Comment by Mic92** [comment]
Your build log contains the output of several package builds. This is a python build. Sops-nix doesn't needs sphinx. The package that fails to build is python and not sops-nix

**Comment by dpolakovics** [comment]
Thank you a lot.
There was a issue with something else.
I need to learn how to debug the building of nix

**Comment by adminy** [comment]
I cannot install python 3.9 on nix because of this KeyError: 'sphinx' ...
I tried both 23.11 and 24.05 ... neither has this fixed. Not sure why this issue is closed as it still persists. @Mic92
This has nothing to do with aws-cli for my case.
